console.log("===Before Swap===");
var name1 = "Sweety";
console.log(name1);
var name2 = "Cutie";
console.log(name2);
var temp = name1;
name1 = name2;
name2 = temp;
console.log("===After swap===");
console.log(name1);
console.log(temp);
console.log("===Before swap Number===");
var num1 = 100;
console.log(num1);
var num2 = 200;
console.log(num2);
var num3 = 300;
console.log(num3);
var temp = num3;
num3 = num2;
num2 = num1;
console.log("===After Swap Number===");
console.log(num3);
console.log(temp);
console.log(num2);
